resource_types:
  - name: serverless-resource
    type: docker-image
    source:
      repository: mclocal.correia.io:5000/marcelocorreia/concourse-serverless-resource
      tag: latest

resources:
  - name: docker-repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: serverless
    type: serverless-resource
    source:
      repository: serverless
      aws_access_key_id: {{aws_access_key_id}}
      aws_secret_access_key: {{aws_secret_access_key}}

jobs:
  - name: deploy
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: docker-repo
        trigger: true
        passed: [docker-build]
      - put: serverless
        params:
          job_dir: 'lambda/hello'
          action: deploy
          extra_params: -s labs

