resource_types:
  - name: serverless-resource
    type: docker-image
    source:
      repository: marcelocorreia/concourse-serverless-resource
      tag: latest

resources:
  - name: docker-repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: docker_image
    type: docker-image
    source:
      repository: {{container_fullname}}
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}
      cache: true

  - name: github_release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo}}
      access_token: {{github_token}}

  - name: serverless
    type: serverless-resource
    source:
      repository: serverless
      aws_access_key_id: {{aws_access_key_id}}
      aws_secret_access_key: {{aws_secret_access_key}}

  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}


jobs:
  - name: docker-resource-build
    serial: true
    build_logs_to_retain: 10
    plan:
      - get: docker-repo
        trigger: true
      - put: resource_version
        params: {bump: patch}
      - put: docker_image
        params:
          build: docker-repo
          tag: resource_version/version
          tag_as_latest: true
      - put: github_release
        params:
          name: resource_version/version
          tag: resource_version/version

  - name: deploy
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: docker-repo
        trigger: true
      - put: serverless
        params:
          job_dir: 'lambda/hello'
          action: deploy

