resource_types:
  - name: serverless-resource
    type: docker-image
    source:
      repository: marcelocorreia/concourse-serverless-resource
      tag: latest

resources:
  - name: git-repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: serverless
    type: serverless-resource
    source:
      repository: serverless
      version: serverless



jobs:
  - name: serverless-resource-release
    build_logs_to_retain: 10
    serial: true
    plan:
      - get: git-repo
        trigger: false
      - put: serverless
        params:
          job_dir: 'lambda/hello'
          text_file: 'lambda/hello/text'
