#!/usr/bin/env bash

set -e
cd "${1}"
exec 3>&1
exec 1>&2
set +x

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > "${payload}" <&0

job_dir="$(jq -r '.params.job_dir// ""' < "${payload}")"
action="$(jq -r '.params.action// ""' < "${payload}")"
aws_access_key_id="$(jq -r '.params.aws_access_key_id// ""' < "${payload}")"
aws_secret_access_key="$(jq -r '.params.aws_secret_access_key// ""' < "${payload}")"

if [  aws_access_key_id != "" ];then
	export AWS_ACCESS_KEY_ID=${aws_access_key_id}
fi

if [  aws_secret_access_key != "" ];then
	export AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
fi


case ${action} in
	deploy)
		cd $(ls)/${job_dir} && serverless deploy
		exit 0
	  ;;
	remove)
		cd ${job_dir} && serverless remove
		exit 0
	  ;;
	delete)
		run
		exit 0
	  ;;

	*)
		echo "ERROR:"
		exit 1
	  ;;
esac

serverless_version="$(jq -n "{serverless_version:{serverless_version:\"$(serverless --version)\"}}")"
timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "$timestamp" $serverless_version| jq -s add  >&3